import {
  HealthCheckResponse,
  Portal,
  Workflow,
  WorkflowRun,
  Document,
  SecurityScan
} from "@/types";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "/api/v1";

async function fetchJson<T>(url: string, options?: RequestInit): Promise<T> {
  const fullUrl = url.startsWith("http") ? url : `${API_BASE}${url}`;
  let attempts = 0;
  let lastError: any = null;

  while (attempts < 3) {
    attempts++;
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 60000); // 60s timeout for Render cold starts

      const res = await fetch(fullUrl, {
        ...options,
        signal: controller.signal,
        headers: {
          "Content-Type": "application/json",
          ...(options?.headers || {}),
        },
      });
      clearTimeout(timeoutId);

      if (!res.ok) {
        const errorText = await res.text();
        throw new Error(`API Error [${res.status}]: ${errorText}`);
      }
      return res.json();
    } catch (err: any) {
      lastError = err;
      if (attempts < 3) {
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    }
  }
  throw new Error(
    lastError?.message || "Failed to connect to backend engine. Please check backend server status."
  );
}

export const api = {
  getHealth: () => fetchJson<HealthCheckResponse>("/health"),

  // Portals
  getPortals: () => fetchJson<Portal[]>("/portals/"),
  createPortal: (data: Partial<Portal>) => fetchJson<Portal>("/portals/", { method: "POST", body: JSON.stringify(data) }),
  testPortalAuth: (id: string) => fetchJson<any>(`/portals/${id}/test-auth`, { method: "POST" }),

  // Workflows
  getWorkflows: () => fetchJson<Workflow[]>("/workflows/"),
  createWorkflow: (data: any) => fetchJson<Workflow>("/workflows/", { method: "POST", body: JSON.stringify(data) }),
  runWorkflow: (id: string, credentials?: { custom_username?: string; custom_password?: string }) =>
    fetchJson<WorkflowRun>(`/workflows/${id}/run`, { method: "POST", body: JSON.stringify(credentials || {}) }),

  // Runs
  getRuns: () => fetchJson<WorkflowRun[]>("/runs/"),
  getRun: (id: string) => fetchJson<WorkflowRun>(`/runs/${id}`),
  getRunLogs: (id: string) => fetchJson<{ run_id: string; status: string; logs: any[] }>(`/runs/${id}/logs`),

  // Documents
  getDocuments: () => fetchJson<Document[]>("/documents/"),
  autoGenerateDocument: (data: { username: string; password: string; document_type: string; paper_format: string }) =>
    fetchJson<any>("/documents/auto-generate", { method: "POST", body: JSON.stringify(data) }),
  renderPdf: (title: string, html_content: string, page_format = "A4") =>
    fetchJson<Document>("/documents/render-pdf", { method: "POST", body: JSON.stringify({ title, html_content, page_format }) }),
  getViewUrl: (id: string) => `${API_BASE}/documents/${id}/view`,
  getDownloadUrl: (id: string) => `${API_BASE}/documents/${id}/download`,

  // Security
  getSecurityScans: () => fetchJson<SecurityScan[]>("/security/"),
  triggerSecurityScan: (portal_id: string) =>
    fetchJson<SecurityScan>("/security/scan", { method: "POST", body: JSON.stringify({ portal_id }) }),
};
