import {
  HealthCheckResponse,
  Portal,
  Workflow,
  WorkflowRun,
  Document,
  SecurityScan
} from "@/types";

// Primary relative API base for Vercel edge proxy, with direct Render HTTPS fallback
const API_BASE = "/api/v1";
const FALLBACK_API_BASE = "https://docflow-automator-backend.onrender.com/api/v1";

async function fetchJson<T>(url: string, options?: RequestInit): Promise<T> {
  const primaryUrl = url.startsWith("http") ? url : `${API_BASE}${url}`;
  const fallbackUrl = url.startsWith("http") ? url : `${FALLBACK_API_BASE}${url}`;

  // Try primary Vercel proxy endpoint first
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 65000);

    const res = await fetch(primaryUrl, {
      ...options,
      signal: controller.signal,
      headers: {
        "Content-Type": "application/json",
        ...(options?.headers || {}),
      },
    });
    clearTimeout(timeoutId);

    if (res.ok) {
      return res.json();
    }
  } catch (primaryErr) {
    console.warn("Primary proxy fetch notice, retrying direct Render backend:", primaryErr);
  }

  // Fallback direct Render HTTPS request
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 80000);

    const res = await fetch(fallbackUrl, {
      ...options,
      signal: controller.signal,
      headers: {
        "Content-Type": "application/json",
        ...(options?.headers || {}),
      },
    });
    clearTimeout(timeoutId);

    if (!res.ok) {
      const errorText = await res.text();
      throw new Error(`API Error [${res.status}]: ${errorText}`);
    }
    return res.json();
  } catch (fallbackErr: any) {
    if (fallbackErr.name === "AbortError") {
      throw new Error("Portal automation execution timed out (server warming up). Please click Generate again.");
    }
    throw new Error(fallbackErr.message || "Failed to connect to backend engine. Please verify server status.");
  }
}

export const api = {
  getHealth: () => fetchJson<HealthCheckResponse>("/health"),

  // Portals
  getPortals: () => fetchJson<Portal[]>("/portals/"),
  createPortal: (data: Partial<Portal>) => fetchJson<Portal>("/portals/", { method: "POST", body: JSON.stringify(data) }),
  testPortalAuth: (id: string) => fetchJson<any>(`/portals/${id}/test-auth`, { method: "POST" }),

  // Workflows
  getWorkflows: () => fetchJson<Workflow[]>("/workflows/"),
  createWorkflow: (data: any) => fetchJson<Workflow>("/workflows/", { method: "POST", body: JSON.stringify(data) }),
  runWorkflow: (id: string, credentials?: { custom_username?: string; custom_password?: string }) =>
    fetchJson<WorkflowRun>(`/workflows/${id}/run`, { method: "POST", body: JSON.stringify(credentials || {}) }),

  // Runs
  getRuns: () => fetchJson<WorkflowRun[]>("/runs/"),
  getRun: (id: string) => fetchJson<WorkflowRun>(`/runs/${id}`),
  getRunLogs: (id: string) => fetchJson<{ run_id: string; status: string; logs: any[] }>(`/runs/${id}/logs`),

  // Documents
  getDocuments: () => fetchJson<Document[]>("/documents/"),
  autoGenerateDocument: (data: { username: string; password: string; document_type: string; paper_format: string }) =>
    fetchJson<any>("/documents/auto-generate", { method: "POST", body: JSON.stringify(data) }),
  renderPdf: (title: string, html_content: string, page_format = "A4") =>
    fetchJson<Document>("/documents/render-pdf", { method: "POST", body: JSON.stringify({ title, html_content, page_format }) }),
  getViewUrl: (id: string) => `${FALLBACK_API_BASE}/documents/${id}/view`,
  getDownloadUrl: (id: string) => `${FALLBACK_API_BASE}/documents/${id}/download`,

  // Security
  getSecurityScans: () => fetchJson<SecurityScan[]>("/security/"),
  triggerSecurityScan: (portal_id: string) =>
    fetchJson<SecurityScan>("/security/scan", { method: "POST", body: JSON.stringify({ portal_id }) }),
};
