"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import {
  Globe2,
  Printer,
  FileText,
  ShieldCheck,
  Zap,
  Activity,
  CheckCircle2,
  Clock,
  ArrowRight,
  RefreshCw,
  KeyRound,
  Download,
  Eye,
  FileCheck,
  ExternalLink
} from "lucide-react";
import { api } from "@/lib/api";
import { Document, WorkflowRun } from "@/types";

export default function DashboardPage() {
  // Form inputs - NO hardcoded values
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [docType, setDocType] = useState("exam");
  const [paperFormat, setPaperFormat] = useState("A5");

  // State
  const [generating, setGenerating] = useState(false);
  const [statusMsg, setStatusMsg] = useState<string | null>(null);
  const [generatedDoc, setGeneratedDoc] = useState<any | null>(null);
  const [recentDocs, setRecentDocs] = useState<Document[]>([]);
  const [recentRuns, setRecentRuns] = useState<WorkflowRun[]>([]);

  const loadDashboardData = async () => {
    try {
      const [dData, rData] = await Promise.all([
        api.getDocuments(),
        api.getRuns()
      ]);
      setRecentDocs(dData);
      setRecentRuns(rData);
    } catch (err) {
      console.error("Data load error:", err);
    }
  };

  useEffect(() => {
    loadDashboardData();
  }, []);

  const handleGenerateDocument = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!username || !password) {
      setStatusMsg("Please enter Student User ID and Portal Password.");
      return;
    }

    // Synchronously open blank tab to bypass browser popup blockers
    let pdfTab: Window | null = null;
    try {
      pdfTab = window.open("about:blank", "_blank");
    } catch (ex) {
      console.warn("Popup block notice:", ex);
    }

    setGenerating(true);
    setGeneratedDoc(null);
    setStatusMsg(`Navigating to FUW portal for ${username}, selecting ${docType.toUpperCase()} and intercepting webview...`);

    try {
      const res = await api.autoGenerateDocument({
        username,
        password,
        document_type: docType,
        paper_format: paperFormat
      });

      setGeneratedDoc(res);
      setStatusMsg("Document successfully captured and converted to 1-page PDF!");

      // Redirect pre-opened tab to the generated PDF URL
      const viewUrl = res.view_url || api.getViewUrl(res.id);
      if (pdfTab && !pdfTab.closed) {
        pdfTab.location.href = viewUrl;
      }

      await loadDashboardData();
    } catch (err: any) {
      if (pdfTab && !pdfTab.closed) {
        pdfTab.close();
      }
      console.error("Auto generate error:", err);
      setStatusMsg(`Generation error: ${err.message || "Failed to generate document. Please check portal credentials."}`);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      {/* Banner */}
      <div className="bg-gradient-to-r from-emerald-950 via-emerald-900 to-green-950 border border-emerald-700/60 rounded-2xl p-6 md:p-8 space-y-3 relative overflow-hidden shadow-2xl emerald-glow">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-emerald-500/20 border border-emerald-400/30 text-emerald-300 text-xs font-mono">
          <Zap className="w-3.5 h-3.5 text-emerald-400" />
          <span>AUTONOMOUS PORTAL DOCUMENT ENGINE</span>
        </div>
        <h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">
          Universal Student Document Auto-Printer & PDF Generator
        </h1>
        <p className="text-emerald-100/80 text-sm max-w-3xl leading-relaxed">
          Input any student's User ID and passcode to automatically log in to Federal University Wukari portal, intercept live document webviews (Exam Cards, Course Forms, Payment Receipts, Results), and export pristine 1-page A4/A5 PDFs that open instantly in your browser.
        </p>
      </div>

      {/* Main Dynamic Document Printing Hub */}
      <div className="bg-emerald-950/80 border border-emerald-800/80 rounded-2xl p-6 space-y-6 shadow-xl">
        <div className="border-b border-emerald-800/60 pb-4 flex items-center justify-between">
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <Printer className="w-5 h-5 text-emerald-400" />
            <span>Generate & Auto-Open Portal Document</span>
          </h2>
          <span className="text-xs font-mono text-emerald-300/70">
            Target: ug.fuwportal.edu.ng
          </span>
        </div>

        <form onSubmit={handleGenerateDocument} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
            {/* User ID */}
            <div className="space-y-2">
              <label className="text-xs font-semibold text-emerald-200 block font-mono">
                Student User ID / Reg No
              </label>
              <input
                type="text"
                required
                placeholder="e.g. ENG/COE/21/013"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full bg-emerald-900/40 border border-emerald-700/80 rounded-xl p-3 text-white font-mono text-sm focus:outline-none focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400"
              />
            </div>

            {/* Password */}
            <div className="space-y-2">
              <label className="text-xs font-semibold text-emerald-200 block font-mono">
                Portal Password
              </label>
              <input
                type="password"
                required
                placeholder="Enter password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full bg-emerald-900/40 border border-emerald-700/80 rounded-xl p-3 text-white font-mono text-sm focus:outline-none focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400"
              />
            </div>

            {/* Document Type Selector */}
            <div className="space-y-2">
              <label className="text-xs font-semibold text-emerald-200 block font-mono">
                Select Document to Print
              </label>
              <select
                value={docType}
                onChange={(e) => {
                  const val = e.target.value;
                  setDocType(val);
                  if (val === "crg" || val === "result") {
                    setPaperFormat("A4");
                  } else {
                    setPaperFormat("A5");
                  }
                }}
                className="w-full bg-emerald-900/40 border border-emerald-700/80 rounded-xl p-3 text-white font-mono text-xs focus:outline-none focus:border-emerald-400"
              >
                <option value="exam">Examination Card & Docket</option>
                <option value="crg">Course Registration Form</option>
                <option value="rec">Official Payment Receipt</option>
                <option value="result">Semester Results Transcript</option>
              </select>
            </div>

            {/* Paper Size Selector */}
            <div className="space-y-2">
              <label className="text-xs font-semibold text-emerald-200 block font-mono">
                Output Paper Format
              </label>
              <select
                value={paperFormat}
                onChange={(e) => setPaperFormat(e.target.value)}
                className="w-full bg-emerald-900/40 border border-emerald-700/80 rounded-xl p-3 text-white font-mono text-xs focus:outline-none focus:border-emerald-400"
              >
                <option value="A5">A5 Format (Compact Docket)</option>
                <option value="A4">A4 Format (Full Sheet)</option>
              </select>
            </div>
          </div>

          <div className="flex items-center justify-between pt-4 border-t border-emerald-800/60">
            <span className="text-xs text-emerald-300/70 font-mono">
              ⚡ PDF opens automatically in a new browser tab upon completion.
            </span>

            <button
              type="submit"
              disabled={generating}
              className="px-6 py-3 rounded-xl bg-gradient-to-r from-emerald-500 to-green-400 hover:from-emerald-400 hover:to-green-300 text-slate-950 font-bold text-sm shadow-lg shadow-emerald-500/20 transition-all flex items-center gap-2 disabled:opacity-50"
            >
              {generating ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin text-slate-950" />
                  <span>Capturing Webview...</span>
                </>
              ) : (
                <>
                  <Printer className="w-4 h-4 text-slate-950" />
                  <span>Generate & Auto-Open PDF</span>
                </>
              )}
            </button>
          </div>
        </form>

        {/* Status Message */}
        {statusMsg && (
          <div className={`p-4 rounded-xl border font-mono text-xs flex items-center justify-between ${
            statusMsg.includes("successfully")
              ? "bg-emerald-900/40 border-emerald-700 text-emerald-300"
              : statusMsg.includes("Navigating")
              ? "bg-emerald-950 border-emerald-800 text-emerald-200"
              : "bg-rose-950/60 border-rose-800 text-rose-300"
          }`}>
            <div className="flex items-center space-x-3">
              {statusMsg.includes("successfully") ? (
                <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
              ) : (
                <Activity className="w-5 h-5 text-emerald-400 shrink-0 animate-pulse" />
              )}
              <span>{statusMsg}</span>
            </div>
            <button onClick={() => setStatusMsg(null)} className="text-emerald-400/60 hover:text-emerald-200">Dismiss</button>
          </div>
        )}

        {/* Generated PDF Card with Instant View & Download Buttons */}
        {generatedDoc && (
          <div className="bg-emerald-900/60 border-2 border-emerald-500 p-5 rounded-xl space-y-4 text-xs font-mono shadow-2xl">
            <div className="flex items-center justify-between border-b border-emerald-800 pb-3">
              <div className="flex items-center space-x-2">
                <FileCheck className="w-5 h-5 text-emerald-400" />
                <span className="font-bold text-white text-sm">{generatedDoc.title}</span>
              </div>
              <span className="px-2.5 py-0.5 rounded bg-emerald-950 text-emerald-300 border border-emerald-700 text-[10px] font-bold">
                {generatedDoc.page_format} 1-PAGE PDF
              </span>
            </div>

            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <span className="text-emerald-200">Size: {Math.round((generatedDoc.file_size_bytes || 1024) / 1024)} KB</span>

              <div className="flex items-center space-x-3">
                <a
                  href={generatedDoc.view_url || api.getViewUrl(generatedDoc.id)}
                  target="_blank"
                  rel="noreferrer"
                  className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs transition-all flex items-center gap-2 shadow-lg shadow-emerald-600/20"
                >
                  <Eye className="w-4 h-4 text-white" />
                  <span>Open & View PDF in Browser</span>
                </a>

                <a
                  href={generatedDoc.download_url || api.getDownloadUrl(generatedDoc.id)}
                  target="_blank"
                  rel="noreferrer"
                  className="px-4 py-2 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs transition-all flex items-center gap-2 shadow-lg shadow-emerald-500/20"
                >
                  <Download className="w-4 h-4 text-slate-950" />
                  <span>Download File</span>
                </a>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Recent Generated PDF Assets */}
      <div className="bg-emerald-950/80 border border-emerald-800/80 rounded-2xl p-6 space-y-4 shadow-xl">
        <div className="flex items-center justify-between border-b border-emerald-800/60 pb-4">
          <h3 className="font-bold text-white text-base flex items-center gap-2">
            <FileText className="w-5 h-5 text-emerald-400" />
            <span>Recent Exported PDF Documents</span>
          </h3>
          <Link href="/documents" className="text-xs text-emerald-400 hover:underline font-mono">
            View Document Studio
          </Link>
        </div>

        {recentDocs.length === 0 ? (
          <div className="text-center py-8 text-emerald-300/50 text-xs font-mono">
            No exported documents yet. Enter student credentials above to test!
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {recentDocs.slice(0, 6).map((doc) => (
              <div key={doc.id} className="bg-emerald-900/30 border border-emerald-800/80 rounded-xl p-4 flex items-center justify-between text-xs">
                <div className="space-y-1 max-w-[60%]">
                  <div className="font-bold text-white truncate">{doc.title}</div>
                  <div className="text-[11px] text-emerald-300/60 font-mono">
                    {doc.page_format} Format • {new Date(doc.created_at).toLocaleDateString()}
                  </div>
                </div>

                <div className="flex items-center space-x-2">
                  <a
                    href={api.getViewUrl(doc.id)}
                    target="_blank"
                    rel="noreferrer"
                    className="p-2 rounded-lg bg-emerald-900/80 hover:bg-emerald-800 text-emerald-300 border border-emerald-700 text-xs transition-all"
                    title="View PDF Inline"
                  >
                    <Eye className="w-3.5 h-3.5" />
                  </a>

                  <a
                    href={api.getDownloadUrl(doc.id)}
                    target="_blank"
                    rel="noreferrer"
                    className="px-3 py-1.5 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs transition-all"
                  >
                    Download
                  </a>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
